# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bde9e4fc2d31829f5d8e501a1d64e8074cf5e00ba981e2a3d0a5835ca6f741d587359528b36c60b4a2d4aa6249e3574e4345f123ba8c7b9f8e0da3bce8a3067

test:
  secret_key_base: be1c249ad2e834258cec38dd9493cd5581f5820c879e9dc341cd8062df77a02be5b475338349694b8adfd053b4ed18cfc5c5fd7f3ddf258c87a785c55743651b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
